name: Deploy Medusa Backend to ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1

      - name: Build and push Docker image
        id: build-image
        run: |
          IMAGE_TAG=medusa-backend:latest
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/medusa-backend:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/medusa-backend:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs_task_definition.json
          service: medusa-backend-service
          cluster: medusa-cluster
          wait-for-service-stability: true

  post-deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Notify via Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,job,commit,repo,ref,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
